# Generated by Django 4.2.6 on 2024-01-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_type_alter_armorial_alliances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legentphotos',
            name='libelle_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
