# Generated by Django 4.2.6 on 2024-01-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_legentphotos_libelle_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='conversation_building',
            new_name='conservation_building',
        ),
        migrations.RenameField(
            model_name='legentphotos',
            old_name='demonstration',
            new_name='denomination',
        ),
        migrations.AddField(
            model_name='armorial',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
